server:
  port: 8892
  servlet:
    context-path: /api-gateway # SCG ignores context-path

profile:
  name: Production

spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://127.0.0.1:8886
          predicates:
            - Path=${server.servlet.context-path}/refresh/book/**, ${server.servlet.context-path}/book/**
          filters:
            - StripPrefix=0
            - RewritePath=${server.servlet.context-path}/refresh(?<segment>/?.*), /book-service/actuator/refresh
            - RewritePath=${server.servlet.context-path}(?<segment>/?.*), /book-service/$\{segment}
        - id: cache-service
          uri: http://127.0.0.1:8883
          predicates:
            - Path=${server.servlet.context-path}/refresh/cache/**, ${server.servlet.context-path}/cache/**
          filters:
            - StripPrefix=0
            - RewritePath=${server.servlet.context-path}/refresh(?<segment>/?.*), /cache-service/actuator/refresh
            - RewritePath=${server.servlet.context-path}(?<segment>/?.*), /cache-service/$\{segment}

cache-service:
  apiKey: dXNlcjpZMkZqYUdVdGMyVnlkbWxqWlE9PQ==
  url: http://127.0.0.1:8883/cache-service/api/cache
  ttl: 10

http:
  time:
    out: 60000

logging:
  file:
    path: ${spring.application.name}/logs/
    name: ${logging.file.path}/${spring.application.name}.log
    max-history: 30
    max-size: 4MB
  level:
    faisal.cloud.app.apigateway: INFO
    reactor.netty: DEBUG
    org.springframework.cloud.gateway: TRACE
  pattern:
    console: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %highlight(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %boldYellow(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
    file: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

management:
  endpoints:
    web:
      exposure:
        include: refresh