server:
  port: 8886
  servlet:
    context-path: /book-service

profile:
  name: Production

book-service:
  auth:
    userName: user
    password: Ym9vay1zZXJ2aWNl
    roles: USER,ADMIN

http:
  time:
    out: 60000

spring:
  datasource:
    driverClassName: org.h2.Driver
    name: book-service
    password:
    platform: h2
    url: jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          import_files: data.sql
        show_sql: true
        use_sql_comments: false

logging:
  file:
    path: ${spring.application.name}/logs/
    name: ${logging.file.path}/${spring.application.name}.log
    max-history: 30
    max-size: 4MB
  level:
    com:
      demo:
        fp:
          bookservice: INFO
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %boldYellow(%logger{36}) - %msg%n'
    file: '%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %boldYellow(%logger{36}) - %msg%n'
